# Generated by Django 4.2.7 on 2024-06-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_shoppingcart_unique_user_product_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Количество'),
        ),
    ]
